# fly.toml app configuration file generated for control-bovino-vfinal on 2025-10-15T10:51:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'control-bovino-vfinal'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  DJANGO_SETTINGS_MODULE = 'cardiaco_vaca.settings'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
