module.exports = {
  apps: [
    {
      name: 'control-bovino-backend',
      script: 'manage.py',
      interpreter: '/home/administrador/ControlBovinoVFinal/venv/bin/python',
      args: 'runserver 0.0.0.0:3000',
      cwd: '/home/administrador/ControlBovinoVFinal/Backend',
      env: {
        PYTHONUNBUFFERED: 1,
        DJANGO_SETTINGS_MODULE: 'cardiaco_vaca.settings',
        DEBUG: 'True',
      },
      env_production: {
        PYTHONUNBUFFERED: 1,
        DJANGO_SETTINGS_MODULE: 'cardiaco_vaca.settings',
        DEBUG: 'False',
      },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '500M',
      error_file: 'logs/error.log',
      out_file: 'logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      watch: ['cardiaco_vaca', 'temp_car'],
      ignore_watch: ['node_modules', 'logs', 'migrations', '__pycache__', '.git'],
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'control-bovino-backend-gunicorn',
      script: '/home/administrador/ControlBovinoVFinal/venv/bin/gunicorn',
      args: 'cardiaco_vaca.wsgi:application --bind 0.0.0.0:3000 --workers 4 --timeout 120',
      cwd: '/home/administrador/ControlBovinoVFinal/Backend',
      env: {
        PYTHONUNBUFFERED: 1,
        DJANGO_SETTINGS_MODULE: 'cardiaco_vaca.settings',
      },
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      error_file: 'logs/gunicorn-error.log',
      out_file: 'logs/gunicorn-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      only: 'production',
    },
  ],

  deploy: {
    production: {
      user: 'node',
      host: 'your-server-ip',
      ref: 'origin/main',
      repo: 'https://github.com/your-org/ControlBovinoVFinal.git',
      path: '/var/www/ControlBovinoVFinal',
      'post-deploy': 'cd Backend && pip install -r requirements.txt && python manage.py migrate && pm2 reload ecosystem.config.js --env production',
    },
  },
};
