# Generated by Django 4.2.13 on 2026-02-02 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bovinos",
            fields=[
                ("id_Bovinos", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idCollar",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="ID del Collar"
                    ),
                ),
                (
                    "macCollar",
                    models.CharField(
                        blank=True,
                        help_text="Dirección MAC del collar sensor",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="MAC del Collar",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "fecha_registro",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el bovino está activo en el sistema",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bovino",
                "verbose_name_plural": "Bovinos",
                "ordering": ["-fecha_registro", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pulsaciones",
            fields=[
                ("id_Pulsaciones", models.AutoField(primary_key=True, serialize=False)),
                ("valor", models.IntegerField()),
            ],
            options={
                "verbose_name": "Pulsación",
                "verbose_name_plural": "Pulsaciones",
            },
        ),
        migrations.CreateModel(
            name="Temperatura",
            fields=[
                ("id_Temperatura", models.AutoField(primary_key=True, serialize=False)),
                ("valor", models.IntegerField()),
            ],
            options={
                "verbose_name": "Temperatura",
                "verbose_name_plural": "Temperaturas",
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Cédula",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información Personal",
                "verbose_name_plural": "Información Personal",
                "ordering": ["apellido", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["cedula"], name="temp_car_pe_cedula_2ad58f_idx"
                    ),
                    models.Index(fields=["email"], name="temp_car_pe_email_c80e32_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                ("id_Lectura", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_lectura",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Lectura",
                    ),
                ),
                (
                    "hora_lectura",
                    models.TimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Hora de Lectura",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("arduino", "Arduino/Collar"),
                            ("app_movil", "App Móvil"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="arduino",
                        help_text="Origen de la lectura: Arduino (collar), App Móvil o Manual",
                        max_length=20,
                        null=True,
                        verbose_name="Fuente de Datos",
                    ),
                ),
                (
                    "id_Bovino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="temp_car.bovinos",
                        verbose_name="Bovino",
                    ),
                ),
                (
                    "id_Pulsaciones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="temp_car.pulsaciones",
                        verbose_name="Pulsaciones",
                    ),
                ),
                (
                    "id_Temperatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="temp_car.temperatura",
                        verbose_name="Temperatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lectura",
                "verbose_name_plural": "Lecturas",
                "ordering": ["-fecha_lectura", "-hora_lectura"],
                "get_latest_by": "fecha_lectura",
            },
        ),
        migrations.CreateModel(
            name="ControlMonitoreo",
            fields=[
                ("id_Control", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_lectura",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Control",
                    ),
                ),
                (
                    "hora_lectura",
                    models.TimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Hora del Control",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del veterinario o encargado",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "accion_tomada",
                    models.CharField(
                        blank=True,
                        help_text="Acción o tratamiento aplicado",
                        max_length=200,
                        null=True,
                        verbose_name="Acción Tomada",
                    ),
                ),
                (
                    "id_Lectura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="temp_car.lectura",
                        verbose_name="Lectura",
                    ),
                ),
                (
                    "id_User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_monitoreo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Monitoreo",
                "verbose_name_plural": "Controles de Monitoreo",
                "ordering": ["-fecha_lectura", "-hora_lectura"],
            },
        ),
        migrations.CreateModel(
            name="ControlManual",
            fields=[
                (
                    "id_ControlManual",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_control",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Control",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("morning", "Mañana (06:00 - 12:00)"),
                            ("afternoon", "Tarde (12:00 - 18:00)"),
                            ("evening", "Noche (18:00 - 23:59)"),
                        ],
                        help_text="Turno del día en que se realiza el control",
                        max_length=10,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "temperatura",
                    models.FloatField(
                        help_text="Temperatura corporal registrada manualmente",
                        validators=[
                            django.core.validators.MinValueValidator(35.0),
                            django.core.validators.MaxValueValidator(42.0),
                        ],
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "pulsaciones",
                    models.IntegerField(
                        help_text="Pulsaciones por minuto registradas manualmente",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Pulsaciones (BPM)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el estado del bovino",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "estado_salud",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal (36-39°C)"),
                            ("Alerta", "Alerta (39-40°C)"),
                            ("Crítico", "Crítico (>40°C)"),
                        ],
                        db_index=True,
                        default="Normal",
                        max_length=20,
                        verbose_name="Estado de Salud",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id_Bovino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_manuales",
                        to="temp_car.bovinos",
                        verbose_name="Bovino",
                    ),
                ),
                (
                    "id_User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_manuales_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Manual",
                "verbose_name_plural": "Controles Manuales",
                "ordering": ["-fecha_control", "-turno"],
            },
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["idCollar"], name="temp_car_bo_idColla_130d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["macCollar"], name="temp_car_bo_macColl_917f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["-fecha_registro"], name="temp_car_bo_fecha_r_c68c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(
                fields=["id_Bovino", "-fecha_lectura", "-hora_lectura"],
                name="temp_car_le_id_Bovi_d315d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(
                fields=["-fecha_lectura", "-hora_lectura"],
                name="temp_car_le_fecha_l_1f2ebf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["id_User", "-fecha_lectura"],
                name="temp_car_co_id_User_614090_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["-fecha_lectura", "-hora_lectura"],
                name="temp_car_co_fecha_l_91e645_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmanual",
            index=models.Index(
                fields=["id_Bovino", "-fecha_control"],
                name="temp_car_co_id_Bovi_d20f27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmanual",
            index=models.Index(
                fields=["-fecha_control", "turno"],
                name="temp_car_co_fecha_c_aaf622_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmanual",
            index=models.Index(
                fields=["id_User", "-fecha_control"],
                name="temp_car_co_id_User_ab65b4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controlmanual",
            unique_together={("id_Bovino", "fecha_control", "turno")},
        ),
    ]
