# Generated by Django 4.2.13 on 2026-02-02 19:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("temp_car", "0001_initial"),
    ]

    operations = [
        # Primero eliminar el modelo ControlManual
        migrations.DeleteModel(
            name="ControlManual",
        ),
        # Luego agregar campos a ControlMonitoreo
        migrations.AddField(
            model_name="controlmonitoreo",
            name="estado_salud",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal (36-39°C)"),
                    ("Alerta", "Alerta (39-40°C)"),
                    ("Crítico", "Crítico (>40°C)"),
                ],
                db_index=True,
                default="Normal",
                help_text="Estado de salud calculado automáticamente",
                max_length=20,
                verbose_name="Estado de Salud",
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de Actualización"
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="pulsaciones",
            field=models.IntegerField(
                blank=True,
                help_text="Pulsaciones por minuto del bovino",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="Pulsaciones (BPM)",
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="temperatura",
            field=models.FloatField(
                blank=True,
                help_text="Temperatura corporal del bovino",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(35.0),
                    django.core.validators.MaxValueValidator(42.0),
                ],
                verbose_name="Temperatura (°C)",
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="turno",
            field=models.CharField(
                choices=[
                    ("morning", "Mañana (06:00 - 12:00)"),
                    ("afternoon", "Tarde (12:00 - 18:00)"),
                    ("evening", "Noche (18:00 - 23:59)"),
                    ("night", "Madrugada (00:00 - 06:00)"),
                ],
                default="morning",
                help_text="Turno del día en que se realiza el control",
                max_length=10,
                verbose_name="Turno",
            ),
        ),
        # Alterar campos en ControlMonitoreo
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="id_Lectura",
            field=models.ForeignKey(
                blank=True,
                help_text="Lectura automática del sensor (puede ser nula para controles puramente manuales)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="temp_car.lectura",
                verbose_name="Lectura",
            ),
        ),
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="id_User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles_monitoreo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registra",
            ),
        ),
        # Agregar constraint unique_together
        migrations.AlterUniqueTogether(
            name="controlmonitoreo",
            unique_together={("id_Lectura", "turno")},
        ),
        # Agregar índices
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["id_Lectura", "turno"], name="temp_car_co_id_Lect_e74855_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["-fecha_lectura", "turno"],
                name="temp_car_co_fecha_l_22ed5d_idx",
            ),
        ),
    ]
