# Generated by Django 4.2.13 on 2026-02-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temp_car", "0002_alter_controlmanual_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovinos",
            name="macCollar",
            field=models.CharField(
                blank=True,
                help_text="Dirección MAC del collar sensor",
                max_length=100,
                null=True,
                verbose_name="MAC del Collar",
            ),
        ),
    ]
