# Generated by Django 4.2.13 on 2026-02-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0003_alter_bovinos_maccollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmonitoreo',
            name='estado_salud',
            field=models.CharField(choices=[('Normal', 'Normal (38.0-39.0°C)'), ('Alerta', 'Alerta (39.0-40.0°C)'), ('Crítico', 'Crítico (>40.0°C)')], db_index=True, default='Normal', help_text='Estado de salud calculado automáticamente', max_length=20, verbose_name='Estado de Salud'),
        ),
    ]
