# Generated by Django 4.2.13 on 2026-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0004_alter_controlmonitoreo_estado_salud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='valor',
            field=models.FloatField(),
        ),
    ]
