# Generated by Django 4.2.25 on 2025-10-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("temp_car", "0004_controlmonitoreo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bovinos",
            options={
                "ordering": ["-fecha_registro", "nombre"],
                "verbose_name": "Bovino",
                "verbose_name_plural": "Bovinos",
            },
        ),
        migrations.AlterModelOptions(
            name="controlmonitoreo",
            options={
                "ordering": ["-fecha_lectura", "-hora_lectura"],
                "verbose_name": "Control de Monitoreo",
                "verbose_name_plural": "Controles de Monitoreo",
            },
        ),
        migrations.AlterModelOptions(
            name="lectura",
            options={
                "get_latest_by": "fecha_lectura",
                "ordering": ["-fecha_lectura", "-hora_lectura"],
                "verbose_name": "Lectura",
                "verbose_name_plural": "Lecturas",
            },
        ),
        migrations.AlterModelOptions(
            name="personalinfo",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Información Personal",
                "verbose_name_plural": "Información Personal",
            },
        ),
        migrations.AlterModelOptions(
            name="pulsaciones",
            options={"verbose_name": "Pulsación", "verbose_name_plural": "Pulsaciones"},
        ),
        migrations.AlterModelOptions(
            name="temperatura",
            options={
                "verbose_name": "Temperatura",
                "verbose_name_plural": "Temperaturas",
            },
        ),
        migrations.AddField(
            model_name="bovinos",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el bovino está activo en el sistema",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="accion_tomada",
            field=models.CharField(
                blank=True,
                help_text="Acción o tratamiento aplicado",
                max_length=200,
                null=True,
                verbose_name="Acción Tomada",
            ),
        ),
        migrations.AddField(
            model_name="controlmonitoreo",
            name="observaciones",
            field=models.TextField(
                blank=True,
                help_text="Observaciones del veterinario o encargado",
                null=True,
                verbose_name="Observaciones",
            ),
        ),
        migrations.AlterField(
            model_name="bovinos",
            name="fecha_registro",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="bovinos",
            name="idCollar",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID del Collar"
            ),
        ),
        migrations.AlterField(
            model_name="bovinos",
            name="macCollar",
            field=models.CharField(
                blank=True,
                help_text="Dirección MAC del collar sensor",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="MAC del Collar",
            ),
        ),
        migrations.AlterField(
            model_name="bovinos",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="fecha_lectura",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha del Control",
            ),
        ),
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="hora_lectura",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Hora del Control"
            ),
        ),
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="id_Lectura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="temp_car.lectura",
                verbose_name="Lectura",
            ),
        ),
        migrations.AlterField(
            model_name="controlmonitoreo",
            name="id_User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles_monitoreo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="fecha_lectura",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Lectura",
            ),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="hora_lectura",
            field=models.TimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Hora de Lectura",
            ),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="id_Bovino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecturas",
                to="temp_car.bovinos",
                verbose_name="Bovino",
            ),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="id_Pulsaciones",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="temp_car.pulsaciones",
                verbose_name="Pulsaciones",
            ),
        ),
        migrations.AlterField(
            model_name="lectura",
            name="id_Temperatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="temp_car.temperatura",
                verbose_name="Temperatura",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="apellido",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Apellido"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="cedula",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Cédula",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="nombre",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["idCollar"], name="temp_car_bo_idColla_130d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["macCollar"], name="temp_car_bo_macColl_917f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bovinos",
            index=models.Index(
                fields=["-fecha_registro"], name="temp_car_bo_fecha_r_c68c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["id_User", "-fecha_lectura"],
                name="temp_car_co_id_User_614090_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="controlmonitoreo",
            index=models.Index(
                fields=["-fecha_lectura", "-hora_lectura"],
                name="temp_car_co_fecha_l_91e645_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(
                fields=["id_Bovino", "-fecha_lectura", "-hora_lectura"],
                name="temp_car_le_id_Bovi_d315d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(
                fields=["-fecha_lectura", "-hora_lectura"],
                name="temp_car_le_fecha_l_1f2ebf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalinfo",
            index=models.Index(fields=["cedula"], name="temp_car_pe_cedula_2ad58f_idx"),
        ),
        migrations.AddIndex(
            model_name="personalinfo",
            index=models.Index(fields=["email"], name="temp_car_pe_email_c80e32_idx"),
        ),
    ]
