# Generated by Django 4.2.13 on 2026-01-15 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "temp_car",
            "0005_alter_bovinos_options_alter_controlmonitoreo_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlManual",
            fields=[
                (
                    "id_ControlManual",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_control",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Control",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("morning", "Mañana (06:00 - 12:00)"),
                            ("afternoon", "Tarde (12:00 - 18:00)"),
                            ("evening", "Noche (18:00 - 23:59)"),
                        ],
                        help_text="Turno del día en que se realiza el control",
                        max_length=10,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "temperatura",
                    models.FloatField(
                        help_text="Temperatura corporal registrada manualmente",
                        validators=[
                            django.core.validators.MinValueValidator(35.0),
                            django.core.validators.MaxValueValidator(42.0),
                        ],
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "pulsaciones",
                    models.IntegerField(
                        help_text="Pulsaciones por minuto registradas manualmente",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Pulsaciones (BPM)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el estado del bovino",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "estado_salud",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal (36-39°C)"),
                            ("Alerta", "Alerta (39-40°C)"),
                            ("Crítico", "Crítico (>40°C)"),
                        ],
                        db_index=True,
                        default="Normal",
                        max_length=20,
                        verbose_name="Estado de Salud",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "id_Bovino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_manuales",
                        to="temp_car.bovinos",
                        verbose_name="Bovino",
                    ),
                ),
                (
                    "id_User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_manuales_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Manual",
                "verbose_name_plural": "Controles Manuales",
                "ordering": ["-fecha_control", "-turno"],
                "indexes": [
                    models.Index(
                        fields=["id_Bovino", "-fecha_control"],
                        name="temp_car_co_id_Bovi_d20f27_idx",
                    ),
                    models.Index(
                        fields=["-fecha_control", "turno"],
                        name="temp_car_co_fecha_c_aaf622_idx",
                    ),
                    models.Index(
                        fields=["id_User", "-fecha_control"],
                        name="temp_car_co_id_User_ab65b4_idx",
                    ),
                ],
                "unique_together": {("id_Bovino", "fecha_control", "turno")},
            },
        ),
    ]
