# Generated by Django 4.2.13 on 2026-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0006_controlmanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='fuente',
            field=models.CharField(blank=True, choices=[('arduino', 'Arduino/Collar'), ('app_movil', 'App Móvil'), ('manual', 'Manual')], db_index=True, default='arduino', help_text='Origen de la lectura: Arduino (collar), App Móvil o Manual', max_length=20, null=True, verbose_name='Fuente de Datos'),
        ),
    ]
